### ISSUE TITLE
Fix the "validate is not a function" error in our installer for yarn

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-agent-js#120]
This has been reported a few times by users:

```
TypeError: validate is not a function
at validateConfig (/Users/fff/.npm/_npx/40929/lib/node_modules/@appland/appmap/built/service/config/validator.js:25:19)
at AgentInstallerProcedure.validateProject (/Users/fff/.npm/_npx/40929/lib/node_modules/@appland/appmap/built/cmds/agentInstaller/agentProcedure.js:95:59)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async AgentInstallerProcedure.run (/Users/fff/.npm/_npx/40929/lib/node_modules/@appland/appmap/built/cmds/agentInstaller/agentInstallerProcedure.js:64:9)
at async _handler (/Users/fff/.npm/_npx/40929/lib/node_modules/@appland/appmap/built/cmds/agentInstaller/install-agent.js:133:17)
```

**Comment by lachrist** [comment]
fix 618ef2a45827ebbb37627ae9ba606d31a17654fb
