### ISSUE TITLE
ENOTDIR: not a directory, chdir

### ISSUE THREAD

**Issue by symwell** [getappmap/appmap-agent-js#132]
Got [this](https://portal.azure.com/#view/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222022-10-20T12%3A27%3A17.216Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222022-10-20T12%3A27%3A17.216Z%22))%20and%20customDimensions%5B%22appmap.cli.sessionId%22%5D%20contains%20%227ee9383e81c2dd97a6326950267f68918a59e50932018d55a60cbf275b62c7c2%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%7C%20project-reorder%20%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog) failure

```
Error: ENOTDIR: not a directory, chdir '/home/test/projects/hash' -> '/home/test/projects/hash/src/client/main.py'
    at process.wrappedChdir (internal/bootstrap/switches/does_own_process_state.js:116:14)
    at process.chdir (/home/test/.npm/_npx/27805/lib/node_modules/@appland/appmap/node_modules/graceful-fs/polyfills.js:22:11)
    at commandFn (/home/test/.npm/_npx/27805/lib/node_modules/@appland/appmap/built/cmds/record/record.js:65:37)
    at runCommand (/home/test/.npm/_npx/27805/lib/node_modules/@appland/appmap/built/cmds/runCommand.js:14:27)
    at Object.handler (/home/test/.npm/_npx/27805/lib/node_modules/@appland/appmap/built/cmds/record/record.js:130:41)
    at /home/test/.npm/_npx/27805/lib/node_modules/@appland/appmap/node_modules/yargs/build/index.cjs:1:8891
    at j (/home/test/.npm/_npx/27805/lib/node_modules/@appland/appmap/node_modules/yargs/build/index.cjs:1:4956)
    at M.handleValidationAndGetResult (/home/test/.npm/_npx/27805/lib/node_modules/@appland/appmap/node_modules/yargs/build/index.cjs:1:8860)
    at M.applyMiddlewareAndGetResult (/home/test/.npm/_npx/27805/lib/node_modules/@appland/appmap/node_modules/yargs/build/index.cjs:1:9502)
    at M.runCommand (/home/test/.npm/_npx/27805/lib/node_modules/@appland/appmap/node_modules/yargs/build/index.cjs:1:7231)
```

Technically it's not a directory, it's a symbolic link.  It may be worth trying to reproduce this.

**Comment by lachrist** [comment]
Wrong repo: I think it should be www.github.com/getappmap/appmap-js

**Comment by symwell** [comment]
Added https://github.com/getappmap/appmap-js/issues/801
