### ISSUE TITLE
`"options.cwd" property must be of type string. Received an instance of URL`

### ISSUE THREAD

**Issue by dividedmind** [getappmap/appmap-agent-js#143]
@lachrist, did you miss a URL object somewhere when you moved to using strings?
```
npx @appland/appmap-agent-js --recorder=mocha -- npx mocha
===
{}
===
(node:2335) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "options.cwd" property must be of type string. Received an instance of URL
at normalizeSpawnArguments (child_process.js:462:11)
at spawnSync (child_process.js:588:8)
at spawn (file:///Users/user/Projects/project/node_modules/@appland/appmap-agent-js/components/repository/node/spawn.mjs?env=node&violation=exit&log-level=error&log-file=2&socket=unix&validate-appmap=off&validate-message=off:16:18)
at extractRepositoryHistory (file:///Users/user/Projects/project/node_modules/@appland/appmap-agent-js/components/repository/node/history.mjs?env=node&violation=exit&log-level=error&log-file=2&socket=unix&validate-appmap=off&validate-message=off:40:19)
at resolveConfigurationRepository (file:///Users/user/Projects/project/node_modules/@appland/appmap-agent-js/components/configuration-accessor/default/index.mjs?env=node&violation=exit&log-level=error&log-file=2&socket=unix&validate-appmap=off&validate-message=off:171:18)
at mainAsync (file:///Users/user/Projects/project/node_modules/@appland/appmap-agent-js/components/batch/default/index.mjs?env=node&violation=exit&log-level=error&log-file=2&socket=unix&validate-appmap=off&validate-message=off:37:19)
at file:///Users/user/Projects/project/node_modules/@appland/appmap-agent-js/lib/node/batch.mjs:28:16
(Use `node --trace-warnings ...` to show where the warning was created)
,(node:2335) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:2335) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lachrist** [comment]
@dividedmind thanks for the report. See URL objects are evil :D. This is probably because the user is running an outdated version of node 14/16. We are only testing against up-to-date node major versions.
