### ISSUE TITLE
TypeError: Invalid URL

### ISSUE THREAD

**Issue by salaryhero-anh** [getappmap/appmap-agent-js#250]
Express application running with babel-node got error: TypeError: Invalid URL

Command: npx appmap-agent-js -- nodemon -r dotenv/config --exec babel-node src/app.js

`[nodemon] starting `babel-node -r dotenv/config src/app.js`
(node:71043) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

(node:71074) ExperimentalWarning: Custom ESM Loaders is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

[appmap@14.2.0] Detected an unknown error. If this error disappears when not recording your application, it is probably an issue within the appmap framework. If this is the case, please consider submitting a bug report at:
  https://github.com/getappmap/appmap-agent-js/issues

node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError: Invalid URL
        at new NodeError (node:internal/errors:405:5)
        at new URL (node:internal/url:611:13)
        at toAbsoluteUrl (file:///Users/anhdn/Desktop/SalaryHero/hris-worker/node_modules/@appland/appmap-agent-js/dist/bundles/recorder-node.mjs:37:3)
        at parseSourcemap (file:///Users/anhdn/Desktop/SalaryHero/hris-worker/node_modules/@appland/appmap-agent-js/dist/bundles/recorder-node.mjs:631:29)
        at extractMissingUrlArray (file:///Users/anhdn/Desktop/SalaryHero/hris-worker/node_modules/@appland/appmap-agent-js/dist/bundles/recorder-node.mjs:1706:31)
        at instrumentInject (file:///Users/anhdn/Desktop/SalaryHero/hris-worker/node_modules/@appland/appmap-agent-js/dist/bundles/recorder-node.mjs:2723:18)
        at instrument (file:///Users/anhdn/Desktop/SalaryHero/hris-worker/node_modules/@appland/appmap-agent-js/dist/bundles/recorder-node.mjs:3164:56)
        at Module._compile (file:///Users/anhdn/Desktop/SalaryHero/hris-worker/node_modules/@appland/appmap-agent-js/dist/bundles/recorder-node.mjs:3917:9)
        at Module._compile (/Users/anhdn/Desktop/SalaryHero/hris-worker/node_modules/pirates/lib/index.js:136:24)
        at Module._extensions..js (node:internal/modules/cjs/loader:1310:10) {
      input: '/Users/anhdn/Desktop/SalaryHero/hris-worker/src/',
      code: 'ERR_INVALID_URL'
}

Node.js v18.17.1
[nodemon] app crashed - waiting for file changes before starting...`

**Comment by brikelly** [comment]
Hi @salaryhero-anh , thank you for logging this issue. We are in the final stages of development of our new NodeJS agent, which is hosted in this repo: https://github.com/getappmap/appmap-node 

If possible, could you check if your issue exists with this new agent instead? We would also just love your feedback on it. It already supports Express.js and Node 18. You can try it with `npx appmap-node@latest <command>`.

Thank you!

**Comment by salaryhero-anh** [comment]
Hi @brikelly, dose this support project using babel?

**Comment by brikelly** [comment]
Hi @salaryhero-anh - Babel should be fine, assuming it's just used for transpiling code. The new Node agent maps JavaScript code regardless of how it came to be :)
