### ISSUE TITLE
java.lang.InternalError: java.lang.ClassNotFoundException: org.apache.http.client.utils.URIBuilder	

### ISSUE THREAD

**Issue by saisumit** [getappmap/appmap-agent-js#252]
I am trying to remotely run app-map on an ECS machine in a dockerized environment. 
I am getting this error : 
`
February 11, 2024 at 15:11 (UTC+5:30) | java.lang.InternalError: java.lang.ClassNotFoundException: org.apache.http.client.utils.URIBuilder | cerebro-development
-- | -- | --
February 11, 2024 at 15:11 (UTC+5:30) | at com.appland.appmap.process.hooks.http.HttpClientRequest.newBuilder(HttpClientRequest.java:92) | cerebro-development
February 11, 2024 at 15:11 (UTC+5:30) | at com.appland.appmap.process.hooks.http.HttpClientRequest.execute(HttpClientRequest.java:43) | cerebro-development
February 11, 2024 at 15:11 (UTC+5:30) | at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java)

`

Here is the docker file: 

```
FROM maven:3.8.4-amazoncorretto-17 AS build
COPY pom.xml /usr/src/cerebro/pom.xml


COPY cerebro-authentication /usr/src/cerebro/cerebro-authentication
COPY cerebro-chain /usr/src/cerebro/cerebro-chain
COPY cerebro-clients /usr/src/cerebro/cerebro-clients
COPY cerebro-common /usr/src/cerebro/cerebro-common
COPY cerebro-core /usr/src/cerebro/cerebro-core
COPY cerebro-data /usr/src/cerebro/cerebro-data
COPY cerebro-entities /usr/src/cerebro/cerebro-entities
COPY cerebro-ethereum /usr/src/cerebro/cerebro-ethereum
COPY cerebro-main /usr/src/cerebro/cerebro-main
COPY cerebro-transaction /usr/src/cerebro/cerebro-transaction
COPY cerebro-users /usr/src/cerebro/cerebro-users
COPY cerebro-proto /usr/src/cerebro/cerebro-proto
COPY cerebro-rulengine /usr/src/cerebro/cerebro-rulengine

RUN mkdir -p /usr/src/appmap

RUN mvn  -f /usr/src/cerebro/pom.xml -e clean install -U
RUN mvn dependency:get -Dartifact=com.appland:appmap-agent:1.25.3 -Ddest=/usr/src/appmap/appmap-agent-1.25.3.jar

FROM amazoncorretto:17.0.1-alpine3.14
USER root
COPY --from=build /usr/src/cerebro/cerebro-main/target/cerebro-main.jar /cerebro-main/cerebro-main.jar
COPY --from=build /usr/src/appmap/appmap-agent-1.25.3.jar /appmap/appmap-agent-1.25.3.jar

RUN chmod 644 /cerebro-main/cerebro-main.jar
RUN chmod 644 /appmap/appmap-agent-1.25.3.jar

EXPOSE 8080
ENTRYPOINT ["java", "-javaagent:/appmap/appmap-agent-1.25.3.jar", "-jar","/cerebro-main/cerebro-main.jar"]
```

**Comment by saisumit** [comment]
Tried installing : https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient/4.5.13 in the root pom but to no avail.
